on:
  release:
    types: [published]

jobs:
  publish:
    name: Pack and Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/janbiehl/TiaGenerator.Core/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build TiaGenerator.Core
      - name: Create the package
        run: dotnet pack --configuration Release TiaGenerator.Core
      - name: Publish the package to GPR
        run: dotnet nuget push TiaGenerator.Core/bin/Release/*.nupkg
